
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class tigerrugAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new tigerrugAddonDeed();
			}
		}

		[ Constructable ]
		public tigerrugAddon()
		{



			AddComplexComponent( (BaseAddon) this, 15325, 0, 1, 0, 0, -1, "Tiger rug", 1);// 1
			AddComplexComponent( (BaseAddon) this, 15326, 0, 0, 0, 0, -1, "Tiger rug", 1);// 2
			AddComplexComponent( (BaseAddon) this, 15327, 1, 0, 0, 0, -1, "Tiger rug", 1);// 3
			AddComplexComponent( (BaseAddon) this, 15328, 1, 1, 0, 0, -1, "Tiger rug", 1);// 4
			AddComplexComponent( (BaseAddon) this, 15329, 0, -1, 0, 0, -1, "Tiger rug", 1);// 5
			AddComplexComponent( (BaseAddon) this, 15330, 1, -1, 0, 0, -1, "Tiger rug", 1);// 6

		}

		public tigerrugAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class tigerrugAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new tigerrugAddon();
			}
		}

		[Constructable]
		public tigerrugAddonDeed()
		{
			Name = "tigerrug";
		}

		public tigerrugAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}