
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class GatewayPortalAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new GatewayPortalAddonDeed();
			}
		}

		[ Constructable ]
		public GatewayPortalAddon()
		{



			AddComplexComponent( (BaseAddon) this, 14480, -3, 0, 0, 0, -1, "Gateway Portal", 1);// 1
			AddComplexComponent( (BaseAddon) this, 14486, 3, 0, 0, 0, -1, "Gateway Portal", 1);// 2
			AddComplexComponent( (BaseAddon) this, 14485, 2, 0, 0, 0, -1, "Gateway Portal", 1);// 3
			AddComplexComponent( (BaseAddon) this, 14484, 1, 0, 0, 0, -1, "Gateway Portal", 1);// 4
			AddComplexComponent( (BaseAddon) this, 14483, 0, 0, 0, 0, -1, "Gateway Portal", 1);// 5
			AddComplexComponent( (BaseAddon) this, 14482, -1, 0, 0, 0, -1, "Gateway Portal", 1);// 6
			AddComplexComponent( (BaseAddon) this, 14481, -2, 0, 0, 0, -1, "Gateway Portal", 1);// 7

		}

		public GatewayPortalAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class GatewayPortalAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new GatewayPortalAddon();
			}
		}

		[Constructable]
		public GatewayPortalAddonDeed()
		{
			Name = "GatewayPortal";
		}

		public GatewayPortalAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}