
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class SandTowerAddon : BaseAddon
	{
         
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new SandTowerAddonDeed();
			}
		}

		[ Constructable ]
		public SandTowerAddon()
		{



			AddComplexComponent( (BaseAddon) this, 8954, 2, 1, 5, 51, -1, "sand tower", 1);// 1
			AddComplexComponent( (BaseAddon) this, 193, 1, -1, 0, 0, -1, "sandbox", 1);// 2
			AddComplexComponent( (BaseAddon) this, 1341, 1, 2, 0, 51, -1, "sand", 1);// 3
			AddComplexComponent( (BaseAddon) this, 1342, 1, 1, 0, 51, -1, "sand", 1);// 4
			AddComplexComponent( (BaseAddon) this, 1341, 1, 0, 0, 51, -1, "sand", 1);// 5
			AddComplexComponent( (BaseAddon) this, 193, 0, -1, 0, 0, -1, "sandbox", 1);// 6
			AddComplexComponent( (BaseAddon) this, 1342, 0, 2, 0, 51, -1, "sand", 1);// 7
			AddComplexComponent( (BaseAddon) this, 1339, 0, 1, 0, 51, -1, "sand", 1);// 8
			AddComplexComponent( (BaseAddon) this, 1340, 0, 0, 0, 51, -1, "sand", 1);// 9
			AddComplexComponent( (BaseAddon) this, 193, 2, 2, 0, 0, -1, "sandbox", 1);// 10
			AddComplexComponent( (BaseAddon) this, 193, 0, 2, 0, 0, -1, "sandbox", 1);// 11
			AddComplexComponent( (BaseAddon) this, 193, 1, 2, 0, 0, -1, "sandbox", 1);// 12
			AddComplexComponent( (BaseAddon) this, 1339, 2, 2, 0, 51, -1, "sand", 1);// 13
			AddComplexComponent( (BaseAddon) this, 1340, 2, 1, 0, 51, -1, "sand", 1);// 14
			AddComplexComponent( (BaseAddon) this, 1340, 2, 0, 0, 51, -1, "sand", 1);// 15
			AddComplexComponent( (BaseAddon) this, 8951, 2, 2, 5, 51, -1, "sand tower", 1);// 16
			AddComplexComponent( (BaseAddon) this, 8952, 1, 2, 5, 51, -1, "sand tower", 1);// 17
			AddComplexComponent( (BaseAddon) this, 8953, 1, 1, 5, 51, -1, "sand tower", 1);// 18
			AddComplexComponent( (BaseAddon) this, 194, -1, 2, 0, 0, -1, "sandbox", 1);// 19
			AddComplexComponent( (BaseAddon) this, 193, 2, -1, 0, 0, -1, "sandbox", 1);// 20
			AddComplexComponent( (BaseAddon) this, 194, -1, 0, 0, 0, -1, "sandbox", 1);// 21
			AddComplexComponent( (BaseAddon) this, 194, -1, 1, 0, 0, -1, "sandbox", 1);// 22
			AddComplexComponent( (BaseAddon) this, 194, 2, 0, 0, 0, -1, "sandbox", 1);// 23
			AddComplexComponent( (BaseAddon) this, 194, 2, 2, 0, 0, -1, "sandbox", 1);// 24
			AddComplexComponent( (BaseAddon) this, 194, 2, 1, 0, 0, -1, "sandbox", 1);// 25

		}

		public SandTowerAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class SandTowerAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new SandTowerAddon();
			}
		}

		[Constructable]
		public SandTowerAddonDeed()
		{
			Name = "Sand Tower Deed";
		}

		public SandTowerAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}