/////////////////////////////////////////////////
//                                             //
// Automatically generated by the              //
// AddonGenerator script by Arya               //
//                                             //
/////////////////////////////////////////////////
namespace Server.Items
{
	public class SmallWaterfallEastAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new SmallWaterfallEastAddonDeed();
			}
		}

		[ Constructable ]
		public SmallWaterfallEastAddon()
		{
			AddonComponent ac;
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 0, -1, 1 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 1, -1, 1 );
			ac = new AddonComponent( 4944 );
			AddComponent( ac, -1, -1, 1 );
			ac = new AddonComponent( 4943 );
			AddComponent( ac, -2, -1, 1 );
			ac = new AddonComponent( 4958 );
			AddComponent( ac, -2, -1, 5 );
			ac = new AddonComponent( 4959 );
			AddComponent( ac, -1, -1, 1 );
			ac = new AddonComponent( 4960 );
			AddComponent( ac, 0, -1, 1 );
			ac = new AddonComponent( 4963 );
			AddComponent( ac, 0, -1, 3 );
			ac = new AddonComponent( 4967 );
			AddComponent( ac, 1, -1, 3 );
			ac = new AddonComponent( 4970 );
			AddComponent( ac, 1, -1, 2 );
			ac = new AddonComponent( 4945 );
			AddComponent( ac, -1, -2, 1 );
			ac = new AddonComponent( 4973 );
			AddComponent( ac, 2, -1, 5 );
			ac = new AddonComponent( 4963 );
			AddComponent( ac, 2, -1, 1 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 2, -1, 1 );
			ac = new AddonComponent( 4967 );
			AddComponent( ac, 3, -1, 3 );
			ac = new AddonComponent( 4970 );
			AddComponent( ac, 3, -1, 1 );
			ac = new AddonComponent( 4943 );
			AddComponent( ac, -3, 3, 1 );
			ac = new AddonComponent( 4944 );
			AddComponent( ac, -2, 3, 1 );
			ac = new AddonComponent( 13422 );
			AddComponent( ac, 1, 0, 2 );
			ac = new AddonComponent( 13422 );
			AddComponent( ac, 1, 1, 2 );
			ac = new AddonComponent( 13422 );
			AddComponent( ac, 1, 2, 2 );
			ac = new AddonComponent( 13555 );
			AddComponent( ac, -1, 2, 1 );
			ac = new AddonComponent( 13555 );
			AddComponent( ac, -1, 1, 1 );
			ac = new AddonComponent( 13555 );
			AddComponent( ac, -1, 0, 1 );
			ac = new AddonComponent( 4959 );
			AddComponent( ac, -1, 3, 9 );
			ac = new AddonComponent( 4960 );
			AddComponent( ac, 0, 3, 9 );
			ac = new AddonComponent( 6002 );
			AddComponent( ac, -2, 2, 5 );
			ac = new AddonComponent( 4963 );
			AddComponent( ac, 0, 3, 1 );
			ac = new AddonComponent( 6001 );
			AddComponent( ac, 1, 3, 1 );
			ac = new AddonComponent( 6002 );
			AddComponent( ac, -3, 1, 2 );
			ac = new AddonComponent( 6006 );
			AddComponent( ac, -2, 0, 3 );
			ac = new AddonComponent( 4962 );
			AddComponent( ac, -1, 3, 1 );
			ac = new AddonComponent( 4956 );
			AddComponent( ac, -3, 0, 5 );
			ac = new AddonComponent( 4963 );
			AddComponent( ac, -2, 2, 1 );
			ac = new AddonComponent( 4963 );
			AddComponent( ac, -1, 0, 14 );
			ac = new AddonComponent( 4967 );
			ac.Hue = 1891;
			AddComponent( ac, -1, 1, 19 );
			ac = new AddonComponent( 4970 );
			AddComponent( ac, -1, 3, 19 );
			ac = new AddonComponent( 6001 );
			AddComponent( ac, -1, 2, 20 );
			ac = new AddonComponent( 4967 );
			AddComponent( ac, 0, 3, 1 );
			ac = new AddonComponent( 6010 );
			ac.Hue = 1885;
			AddComponent( ac, -3, 0, 0 );
			ac = new AddonComponent( 13451 );
			AddComponent( ac, 1, 0, 3 );
			ac = new AddonComponent( 3219 );
			AddComponent( ac, -1, 3, 14 );
			ac = new AddonComponent( 6009 );
			AddComponent( ac, 3, 0, 3 );
			ac = new AddonComponent( 4963 );
			AddComponent( ac, 3, 1, 3 );
			ac = new AddonComponent( 4967 );
			AddComponent( ac, 3, 2, 3 );
			ac = new AddonComponent( 4970 );
			AddComponent( ac, 3, 3, 7 );
			ac = new AddonComponent( 4967 );
			AddComponent( ac, 3, 3, 7 );
			ac = new AddonComponent( 13422 );
			AddComponent( ac, 2, 2, 2 );
			ac = new AddonComponent( 13422 );
			AddComponent( ac, 2, 1, 2 );
			ac = new AddonComponent( 13422 );
			AddComponent( ac, 2, 0, 2 );
			ac = new AddonComponent( 4962 );
			AddComponent( ac, 2, 3, 2 );
			ac = new AddonComponent( 4963 );
			AddComponent( ac, 3, 3, 2 );
			ac = new AddonComponent( 3248 );
			AddComponent( ac, 3, 0, 8 );
			ac = new AddonComponent( 13573 );
			AddComponent( ac, 0, 2, 1 );
			ac = new AddonComponent( 13573 );
			AddComponent( ac, 0, 1, 1 );
			ac = new AddonComponent( 13573 );
			AddComponent( ac, 0, 0, 1 );

		}

		public SmallWaterfallEastAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class SmallWaterfallEastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new SmallWaterfallEastAddon();
			}
		}

		[Constructable]
		public SmallWaterfallEastAddonDeed()
		{
			Name = "SmallWaterfallEast";
		}

		public SmallWaterfallEastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}