/////////////////////////////////////////////////
//
// Created With Statics By seanandre And
// Automatically generated by
// Addon Script Generator by Arya
//
/////////////////////////////////////////////////
namespace Server.Items
{
	public class StarGateAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new StarGateAddonDeed();
			}
		}

		[ Constructable ]
		public StarGateAddon()
		{
			AddComponent( new AddonComponent( 1958 ), -1, -1, 0 );
			AddComponent( new AddonComponent( 1955 ), -1, 0, 0 );
			AddComponent( new AddonComponent( 1955 ), -1, 0, 25 );
			AddComponent( new AddonComponent( 1959 ), -1, 0, 30 );
			AddComponent( new AddonComponent( 1955 ), 0, 0, 0 );
			AddComponent( new AddonComponent( 1955 ), 0, 0, 25 );
			AddComponent( new AddonComponent( 1955 ), 0, 0, 30 );
			AddComponent( new AddonComponent( 1958 ), 0, -1, 0 );
			AddComponent( new AddonComponent( 1955 ), -2, 0, 0 );
			AddComponent( new AddonComponent( 1955 ), -2, 0, 5 );
			AddComponent( new AddonComponent( 1955 ), -2, 0, 10 );
			AddComponent( new AddonComponent( 1955 ), -2, 0, 15 );
			AddComponent( new AddonComponent( 1955 ), -2, 0, 20 );
			AddComponent( new AddonComponent( 1959 ), -2, 0, 25 );
			AddComponent( new AddonComponent( 1960 ), -2, -1, 0 );
			AddComponent( new AddonComponent( 1958 ), 1, -1, 0 );
			AddComponent( new AddonComponent( 1955 ), 1, 0, 0 );
			AddComponent( new AddonComponent( 1955 ), 1, 0, 25 );
			AddComponent( new AddonComponent( 1957 ), 1, 0, 30 );
			AddComponent( new AddonComponent( 1956 ), 1, 1, 0 );
			AddComponent( new AddonComponent( 1956 ), 0, 1, 0 );
			AddComponent( new AddonComponent( 1961 ), 2, 1, 0 );
			AddComponent( new AddonComponent( 1955 ), 2, 0, 0 );
			AddComponent( new AddonComponent( 1955 ), 2, 0, 5 );
			AddComponent( new AddonComponent( 1955 ), 2, 0, 10 );
			AddComponent( new AddonComponent( 1955 ), 2, 0, 15 );
			AddComponent( new AddonComponent( 1955 ), 2, 0, 20 );
			AddComponent( new AddonComponent( 1957 ), 2, 0, 25 );
			AddComponent( new AddonComponent( 1962 ), 2, -1, 0 );
			AddComponent( new AddonComponent( 1956 ), -1, 1, 0 );
			AddComponent( new AddonComponent( 1963 ), -2, 1, 0 );
			AddonComponent ac = null;
			ac = new AddonComponent( 1955 );
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 1960 );
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 1958 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 1958 );
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 1958 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 1955 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 1955 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 1955 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 1955 );
			AddComponent( ac, -2, 0, 5 );
			ac = new AddonComponent( 1955 );
			AddComponent( ac, -2, 0, 10 );
			ac = new AddonComponent( 1955 );
			AddComponent( ac, -2, 0, 15 );
			ac = new AddonComponent( 1955 );
			AddComponent( ac, -2, 0, 20 );
			ac = new AddonComponent( 1959 );
			AddComponent( ac, -2, 0, 25 );
			ac = new AddonComponent( 1955 );
			AddComponent( ac, 1, 0, 25 );
			ac = new AddonComponent( 1955 );
			AddComponent( ac, 0, 0, 25 );
			ac = new AddonComponent( 1955 );
			AddComponent( ac, -1, 0, 25 );
			ac = new AddonComponent( 1957 );
			AddComponent( ac, 1, 0, 30 );
			ac = new AddonComponent( 1959 );
			AddComponent( ac, -1, 0, 30 );
			ac = new AddonComponent( 1955 );
			AddComponent( ac, 0, 0, 30 );
			ac = new AddonComponent( 6732 );
			ac.Hue = 1152;
			AddComponent( ac, 1, 0, 15 );
			ac = new AddonComponent( 6732 );
			ac.Hue = 1152;
			AddComponent( ac, 0, 0, 15 );
			ac = new AddonComponent( 6732 );
			ac.Hue = 1152;
			AddComponent( ac, -1, 0, 15 );
			ac = new AddonComponent( 6732 );
			ac.Hue = 1152;
			AddComponent( ac, -1, 0, 5 );
			ac = new AddonComponent( 6732 );
			ac.Hue = 1152;
			AddComponent( ac, 0, 0, 5 );
			ac = new AddonComponent( 6732 );
			ac.Hue = 1152;
			AddComponent( ac, 1, 0, 5 );
		}

		public StarGateAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class StarGateAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new StarGateAddon();
			}
		}

		[Constructable]
		public StarGateAddonDeed()
		{
			Name = "StarGate";
		}

		public StarGateAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}