/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class GoldCanopySetAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new GoldCanopySetAddonDeed();
			}
		}

		[ Constructable ]
		public GoldCanopySetAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 9375 );
			AddComponent( ac, -3, 3, 16 );
			ac = new AddonComponent( 9375 );
			AddComponent( ac, -3, 1, 16 );
			ac = new AddonComponent( 2777 );
			ac.Hue = 1965;
			AddComponent( ac, -1, 3, 0 );
			ac = new AddonComponent( 2775 );
			ac.Hue = 1965;
			AddComponent( ac, -1, -3, 0 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 1965;
			AddComponent( ac, 1, -2, 0 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 1965;
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 1965;
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 1965;
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 1965;
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 1965;
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 1965;
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 1965;
			AddComponent( ac, -2, 1, 0 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 1965;
			AddComponent( ac, -2, 0, 0 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 1965;
			AddComponent( ac, -2, -1, 0 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 1965;
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 9376 );
			AddComponent( ac, -1, -3, 16 );
			ac = new AddonComponent( 2777 );
			ac.Hue = 1965;
			AddComponent( ac, 2, 3, 0 );
			ac = new AddonComponent( 2777 );
			ac.Hue = 1965;
			AddComponent( ac, 1, 3, 0 );
			ac = new AddonComponent( 2777 );
			ac.Hue = 1965;
			AddComponent( ac, 0, 3, 0 );
			ac = new AddonComponent( 2774 );
			ac.Hue = 1965;
			AddComponent( ac, -3, 2, 0 );
			ac = new AddonComponent( 2774 );
			ac.Hue = 1965;
			AddComponent( ac, -3, 1, 0 );
			ac = new AddonComponent( 2777 );
			ac.Hue = 1965;
			AddComponent( ac, -2, 3, 0 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 1965;
			AddComponent( ac, 2, -1, 0 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 1965;
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 5645 );
			ac.Hue = 1965;
			AddComponent( ac, -2, 3, 0 );
			ac = new AddonComponent( 5645 );
			ac.Hue = 1965;
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 5646 );
			ac.Hue = 1965;
			AddComponent( ac, -2, 4, 0 );
			ac = new AddonComponent( 5646 );
			ac.Hue = 1965;
			AddComponent( ac, 3, 4, 0 );
			ac = new AddonComponent( 2842 );
			ac.Light = LightType.Circle225;
			AddComponent( ac, -2, -2, 6 );
			ac = new AddonComponent( 5646 );
			ac.Hue = 1965;
			AddComponent( ac, 3, -2, 0 );
			ac = new AddonComponent( 2874 );
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 5646 );
			ac.Hue = 1965;
			AddComponent( ac, -2, -2, 0 );
			ac = new AddonComponent( 9376 );
			AddComponent( ac, 3, -3, 16 );
			ac = new AddonComponent( 9376 );
			AddComponent( ac, 2, -3, 16 );
			ac = new AddonComponent( 9376 );
			AddComponent( ac, 1, -3, 16 );
			ac = new AddonComponent( 9376 );
			AddComponent( ac, 0, -3, 16 );
			ac = new AddonComponent( 9376 );
			AddComponent( ac, -2, -3, 16 );
			ac = new AddonComponent( 9376 );
			AddComponent( ac, 3, 3, 16 );
			ac = new AddonComponent( 9376 );
			AddComponent( ac, 2, 3, 16 );
			ac = new AddonComponent( 9376 );
			AddComponent( ac, 1, 3, 16 );
			ac = new AddonComponent( 9376 );
			AddComponent( ac, 0, 3, 16 );
			ac = new AddonComponent( 9376 );
			AddComponent( ac, -1, 3, 16 );
			ac = new AddonComponent( 9376 );
			AddComponent( ac, -2, 3, 16 );
			ac = new AddonComponent( 9375 );
			AddComponent( ac, -3, 2, 16 );
			ac = new AddonComponent( 9375 );
			AddComponent( ac, -3, 0, 16 );
			ac = new AddonComponent( 9375 );
			AddComponent( ac, -3, -1, 16 );
			ac = new AddonComponent( 9375 );
			AddComponent( ac, -3, -2, 16 );
			ac = new AddonComponent( 9375 );
			AddComponent( ac, 3, 3, 16 );
			ac = new AddonComponent( 9375 );
			AddComponent( ac, 3, 2, 16 );
			ac = new AddonComponent( 9375 );
			AddComponent( ac, 3, 1, 16 );
			ac = new AddonComponent( 9375 );
			AddComponent( ac, 3, 0, 16 );
			ac = new AddonComponent( 9375 );
			AddComponent( ac, 3, -1, 16 );
			ac = new AddonComponent( 9375 );
			AddComponent( ac, 3, -2, 16 );
			ac = new AddonComponent( 2776 );
			ac.Hue = 1965;
			AddComponent( ac, 3, 2, 0 );
			ac = new AddonComponent( 2776 );
			ac.Hue = 1965;
			AddComponent( ac, 3, 1, 0 );
			ac = new AddonComponent( 2776 );
			ac.Hue = 1965;
			AddComponent( ac, 3, 0, 0 );
			ac = new AddonComponent( 2776 );
			ac.Hue = 1965;
			AddComponent( ac, 3, -1, 0 );
			ac = new AddonComponent( 2776 );
			ac.Hue = 1965;
			AddComponent( ac, 3, -2, 0 );
			ac = new AddonComponent( 2775 );
			ac.Hue = 1965;
			AddComponent( ac, 2, -3, 0 );
			ac = new AddonComponent( 2775 );
			ac.Hue = 1965;
			AddComponent( ac, 1, -3, 0 );
			ac = new AddonComponent( 2775 );
			ac.Hue = 1965;
			AddComponent( ac, 0, -3, 0 );
			ac = new AddonComponent( 2775 );
			ac.Hue = 1965;
			AddComponent( ac, -2, -3, 0 );
			ac = new AddonComponent( 2774 );
			ac.Hue = 1965;
			AddComponent( ac, -3, 0, 0 );
			ac = new AddonComponent( 2774 );
			ac.Hue = 1965;
			AddComponent( ac, -3, -1, 0 );
			ac = new AddonComponent( 2774 );
			ac.Hue = 1965;
			AddComponent( ac, -3, -2, 0 );
			ac = new AddonComponent( 2773 );
			ac.Hue = 1965;
			AddComponent( ac, 3, -3, 0 );
			ac = new AddonComponent( 2772 );
			ac.Hue = 1965;
			AddComponent( ac, -3, 3, 0 );
			ac = new AddonComponent( 2771 );
			ac.Hue = 1965;
			AddComponent( ac, -3, -3, 0 );
			ac = new AddonComponent( 2770 );
			ac.Hue = 1965;
			AddComponent( ac, 3, 3, 0 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 1965;
			AddComponent( ac, 2, 2, 0 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 1965;
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 1965;
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 1965;
			AddComponent( ac, 2, -2, 0 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 1965;
			AddComponent( ac, 1, 2, 0 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 1965;
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 1965;
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 1965;
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 1965;
			AddComponent( ac, 0, -2, 0 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 1965;
			AddComponent( ac, -1, 2, 0 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 1965;
			AddComponent( ac, -1, -2, 0 );
			ac = new AddonComponent( 2769 );
			ac.Hue = 1965;
			AddComponent( ac, -2, 2, 0 );
			ac = new AddonComponent( 2330 );
			ac.Hue = 2255;
			AddComponent( ac, -2, -2, 9 );
			ac = new AddonComponent( 10806 );
			AddComponent( ac, 3, 3, 0 );
			ac = new AddonComponent( 10806 );
			AddComponent( ac, 3, -3, 0 );
			ac = new AddonComponent( 10806 );
			AddComponent( ac, -3, -3, 0 );
			ac = new AddonComponent( 10806 );
			AddComponent( ac, -3, 3, 0 );
			ac = new AddonComponent( 5645 );
			ac.Hue = 1965;
			AddComponent( ac, 4, 3, 0 );
			ac = new AddonComponent( 5645 );
			ac.Hue = 1965;
			AddComponent( ac, 4, -2, 0 );

		}

		public GoldCanopySetAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class GoldCanopySetAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new GoldCanopySetAddon();
			}
		}

		[Constructable]
		public GoldCanopySetAddonDeed()
		{
			Name = "Gold Canopy Set";
		}

		public GoldCanopySetAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}