#region AuthorHeader
//
//	Shrink System version 2.1, by Xanthos
//
//
#endregion AuthorHeader

using System;
using Server.Mobiles;

namespace Xanthos.ShrinkSystem
{
	// This file is for configuration of the Shrink System.  It is advised
	// that you DO NOT edit this file, instead place ShrinkConfig.xml in the 
	// RunUO/Data directory and modify the values there to configure the system
	// without changing code.  This allows you to take updates to the system
	// without losing your specific configuration settings.

	public class ShrinkConfig
	{
		public enum BlessStatus
		{
			All,		// All shrink items are blessed
			BondedOnly,	// Only shrink items for bonded pets are blessed
			None		// No shrink items are blessed
		}

		public static bool PetAsStatuette = true;		// Deed or statuette form
		public static bool AllowLocking = false;		// Allow players to lock the shrunken pet or not
		public static bool ShowPetDetails = false;		// Show stats and skills on the properties of the shrunken pet
		public static double ShrunkenWeight = 10.0;
		public static bool BlessedLeash = false;
		public static BlessStatus LootStatus = BlessStatus.None;	// How the shruken pet should be as loot
		public static double TamingRequired = 0;		// set to zero for no skill requirement to use shrink tools
		public static int ShrinkCharges = -1;			// set to -1 for infinite uses

		public static Type[] PackAnimals = new Type []
		{
			typeof(PackHorse),
			typeof(PackLlama),
			typeof(Beetle),
		};
	}
}