/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
namespace Server.Items
{
	public class ClothcouchSAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new ClothcouchSAddonDeed();
			}
		}

		[ Constructable ]
		public ClothcouchSAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 1113 );
			ac.Hue = 46;
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 1113 );
			ac.Hue = 46;
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 1113 );
			ac.Hue = 46;
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 10386 );
			ac.Hue = 46;
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 10386 );
			ac.Hue = 46;
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 10386 );
			ac.Hue = 46;
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 10382 );
			ac.Hue = 46;
			AddComponent( ac, 2, 1, 1 );
			ac = new AddonComponent( 10382 );
			ac.Hue = 46;
			AddComponent( ac, -1, 1, 1 );
			ac = new AddonComponent( 10380 );
			ac.Hue = 46;
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 5031 );
			ac.Hue = 46;
			AddComponent( ac, 2, 1, 1 );
			ac = new AddonComponent( 5030 );
			ac.Hue = 46;
			AddComponent( ac, 2, 1, 5 );

		}

		public ClothcouchSAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class ClothcouchSAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new ClothcouchSAddon();
			}
		}

		[Constructable]
		public ClothcouchSAddonDeed()
		{
			Name = "ClothcouchS";
		}

		public ClothcouchSAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}