/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
namespace Server.Items
{
	public class ClothchairEAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new ClothchairEAddonDeed();
			}
		}

		[ Constructable ]
		public ClothchairEAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 1114 );
			ac.Hue = 46;
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 1114 );
			ac.Hue = 46;
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 10383 );
			ac.Hue = 46;
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 10383 );
			ac.Hue = 46;
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 10385 );
			ac.Hue = 46;
			AddComponent( ac, 1, 1, 1 );
			ac = new AddonComponent( 10385 );
			ac.Hue = 46;
			AddComponent( ac, 1, -1, 1 );
			ac = new AddonComponent( 10380 );
			ac.Hue = 46;
			AddComponent( ac, 0, -1, 0 );
			ac = new AddonComponent( 5030 );
			ac.Hue = 46;
			AddComponent( ac, 1, 1, 3 );
			ac = new AddonComponent( 5031 );
			ac.Hue = 46;
			AddComponent( ac, 1, 1, 4 );

		}

		public ClothchairEAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class ClothchairEAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new ClothchairEAddon();
			}
		}

		[Constructable]
		public ClothchairEAddonDeed()
		{
			Name = "ClothchairE";
		}

		public ClothchairEAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}