/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
namespace Server.Items
{
	public class OrnatecouchSAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new OrnatecouchSAddonDeed();
			}
		}

		[ Constructable ]
		public OrnatecouchSAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 11727 );
			ac.Hue = 46;
			AddComponent( ac, -1, 1, 1 );
			ac = new AddonComponent( 11727 );
			ac.Hue = 46;
			AddComponent( ac, 2, 1, 1 );
			ac = new AddonComponent( 11728 );
			ac.Hue = 46;
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 11728 );
			ac.Hue = 46;
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 11728 );
			ac.Hue = 46;
			AddComponent( ac, 2, 0, 0 );
			ac = new AddonComponent( 11718 );
			ac.Hue = 46;
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 1113 );
			ac.Hue = 46;
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 1113 );
			ac.Hue = 46;
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 1113 );
			ac.Hue = 46;
			AddComponent( ac, 2, 1, 0 );
			ac = new AddonComponent( 11504 );
			ac.Hue = 46;
			AddComponent( ac, 0, 0, 5 );
			ac = new AddonComponent( 11504 );
			ac.Hue = 46;
			AddComponent( ac, 1, 0, 5 );
			ac = new AddonComponent( 11504 );
			ac.Hue = 46;
			AddComponent( ac, 2, 0, 5 );
			ac = new AddonComponent( 11210 );
			ac.Hue = 46;
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 5035 );
			ac.Hue = 46;
			AddComponent( ac, 2, 1, 5 );

		}

		public OrnatecouchSAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class OrnatecouchSAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new OrnatecouchSAddon();
			}
		}

		[Constructable]
		public OrnatecouchSAddonDeed()
		{
			Name = "OrnatecouchS";
		}

		public OrnatecouchSAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}